Don't loop endlessly if dbus-daemon fails or is missing.

diff --git a/test/test_server b/test/test_server
--- a/test/test_server
+++ b/test/test_server
@@ -26,7 +26,12 @@ my_dbus_launch () {
 
     dbus-daemon --session --print-address=3 3>$AF --print-pid=4 4>$PF &
     # wait for the daemon to print the info
-    while [ ! -s $AF -a ! -s $PF ]; do sleep 0.1; done
+    TRIES=0
+    while [ ! -s $AF -o ! -s $PF ]; do
+	sleep 0.1
+	TRIES=`expr $TRIES + 1`
+	if [ $TRIES -gt 100 ]; then echo "dbus-daemon failed?"; exit 1; fi
+    done
     DBUS_SESSION_BUS_PID=$(cat $PF)
     export DBUS_SESSION_BUS_ADDRESS=$(cat $AF)
     # Clean up at exit. This will also kill the server.
